config/routes.rb
Rails.application.routes.draw do
  get 'archives/index'
  resources :entries
  root to: "entries#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/entry.rb
class Entry < ApplicationRecord
  
  def day
    self.created_at.strftime("%b %e, %Y")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  def index
    @entries = Entry.all.group_by(&:day)
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: %i[ show edit update destroy ]

  # GET /entries or /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1 or /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries or /entries.json
  def create
    @entry = Entry.new(entry_params)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully created." }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1 or /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to entry_url(@entry), notice: "Entry was successfully updated." }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1 or /entries/1.json
  def destroy
    @entry.destroy

    respond_to do |format|
      format.html { redirect_to entries_url, notice: "Entry was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def entry_params
      params.require(:entry).permit(:meal_type, :calories, :proteins, :carbohydrates, :fats)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/archives_helper.rb
module ArchivesHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/archives/index.html.erb
<div class="columns is-centered mt-6">
    <div class="column is-half">
        <% @entries.each do |day, entries| %>
            <h3>Entries for <%= day %> </h3>

        <nav class="level is-mobile">
            <div class="level-item has-text-centered">
                <div>
                    <p class="heading">Calories</p>
                    <p class="title"><%= entries.pluck(:calories).sum %> </p>
                </div>
            </div>    
            <div class="level-item has-text-centered">
                <div>
                    <p class="heading">proteins</p>
                    <p class="title"><%= entries.pluck(:proteins).sum %>g</p>
                </div>
            </div>
            <div class="level-item has-text-centered">
                <div>
                    <p class="heading">carbs</p>
                    <p class="title"><%= entries.pluck(:carbohydrates).sum %>g </p>
                </div>
            </div>
            <div class="level-item has-text-centered">
                <div>
                    <p class="heading">fats</p>
                    <p class="title"><%= entries.pluck(:fats).sum %>g</p>
                </div>
            </div>
        </nav>
            
            <% entries.each do |entry| %>
                <%= link_to entry_path(entry) do %>
                <div class="card">
                    <div class="card-content">
                        <strong> <%= entry.meal_type %> </strong> <br/>
                        <%= entry.calories %> calories, 
                        <%= entry.proteins %> proteins,
                        <%= entry.carbohydrates %> carbs,
                        <%= entry.fats %> fats,
                    </div>
                </div>
                 <% end %>
             <% end %>
        <% end %>
    </div>
</div>

app/views/entries/_entry.html.erb
<div id="<%= dom_id entry %>">
  <p>
    <strong>Meal type:</strong>
    <%= entry.meal_type %>
  </p>

  <p>
    <strong>Calories:</strong>
    <%= entry.calories %>
  </p>

  <p>
    <strong>Proteins:</strong>
    <%= entry.proteins %>
  </p>

  <p>
    <strong>Carbohydrates:</strong>
    <%= entry.carbohydrates %>
  </p>

  <p>
    <strong>Fats:</strong>
    <%= entry.fats %>
  </p>

</div>

app/views/entries/_form.html.erb
<%= form_with(model: entry) do |form| %>
  <% if entry.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
        <% entry.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :meal_type, style: "display: block" %>
    <%= form.text_field :meal_type %>
  </div>

  <div>
    <%= form.label :calories, style: "display: block" %>
    <%= form.number_field :calories %>
  </div>

  <div>
    <%= form.label :proteins, style: "display: block" %>
    <%= form.number_field :proteins %>
  </div>

  <div>
    <%= form.label :carbohydrates, style: "display: block" %>
    <%= form.number_field :carbohydrates %>
  </div>

  <div>
    <%= form.label :fats, style: "display: block" %>
    <%= form.number_field :fats %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing entry</h1>

<%= render "form", entry: @entry %>

<br>

<div>
  <%= link_to "Show this entry", @entry %> |
  <%= link_to "Back to entries", entries_path %>
</div>

app/views/entries/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="columns mt-6 is-centered">
  <% @entries.each do |entry| %>
    <div class="column is-one-quarter">  
      <div class="card">
        <header class="card-header">
         <p class="card-header-title"> <%= entry.meal_type %> </p>
        </header>
        <div class="card-content">
          <div class="content">
            <p><span class="has-text-weight-bold"> <%= entry.calories %></span> calories</p>
            <p><span class="has-text-weight-bold"> <%= entry.proteins %></span>grams of proteins</p>
            <p><span class="has-text-weight-bold"> <%= entry.carbohydrates %></span>grams of carbohydrates</p>
            <p><span class="has-text-weight-bold"> <%= entry.fats %></span>grams of fats</p>
            <p class="italic">Logged <%= time_ago_in_words(entry.created_at) %> ago</p>
          </div>
        </div>
        <div class="card-footer">
          <%= link_to 'Show', entry, class: "card-footer-item" %>
          <%= link_to 'Edit', edit_entry_path(entry), class: "card-footer-item" %>
          <%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' }, class: "card-footer-item" %>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="columns is-centered mt-6">
  <%= link_to "View all entries", archives_index_path %>
</div>

app/views/entries/new.html.erb
<h1>New entry</h1>

<%= render "form", entry: @entry %>

<br>

<div>
  <%= link_to "Back to entries", entries_path %>
</div>

app/views/entries/show.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title do %>
  <%= @entry.meal_type %>
<% end %>

<%= render @entry %>

<div>
  <%= link_to "Edit this entry", edit_entry_path(@entry) %> |
  <%= link_to "Back to entries", entries_path %>

  <%= button_to "Destroy this entry", @entry, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Webapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render "shared/header" %>

    <div class="container"> 
      <%= yield %>
    </div>
  </body>
</html>

app/views/shared/_header.html.erb
<section class="hero is-link is-small">
  <!-- Hero head: will stick at the top -->
  <div class="hero-head">
    <nav class="navbar">
      <div class="container">
        <div class="navbar-brand">
          <%# <a class="navbar-item">
            <img src="https://bulma.io/images/bulma-type-white.png" alt="Logo">
          </a> %>
          <%= link_to root_path, class: "navbar-item" do %>
            <span class="has-text-weight-bold is-size-4 ml-4">Foodlog</span>
          <% end %>
          <span class="navbar-burger" data-target="navbarMenuHeroA">
            <span></span>
            <span></span>
            <span></span>
          </span>
        </div>
        <div id="navbarMenuHeroA" class="navbar-menu">
          <div class="navbar-end">
            <span class="navbar-item">
              <%= link_to "Create new entry", new_entry_path, class: "button is-success" %>
            </span>
          </div>
        </div>
      </div>
    </nav>
  </div>

  <!-- Hero content: will be in the middle -->
  <div class="hero-body">
    <div class="container has-text-centered">
      <h1 class="title">
        <% if content_for(:title) %>
          <%= yield :title %>
        <% else %>
          Foodlog
        <% end %>
      </h1>
    </div>
  </div>

</section>